### PR TITLE
Display dependency information

### PR DESCRIPTION
**Pull request by duncanjbrown**
Track Rails and Ruby versions across Teacher Services, and track uptake of our favourite internal libraries. Depends on #37 but could be merged instead.

Add a few services that were missing.

Screenshot 2022-07-01 at 17 07 26

### CODE REVIEW

**Review by benilovj — APPROVED** [review]
The dependency table view is neat and looks useful.

Code seems sensible to me.

**Comment by duncanjbrown** [comment]
Thanks @benilovj !

**Comment by aje54** [comment]
Looks very useful and a good example that we could use to create a .Net version of this.

**Comment by aje54** [comment]
packages.lock.json

**Pull request merged**
